In [53]:
import numpy as np

In [54]:
a= np.random.randint(1,100,15)

In [55]:
a

array([65, 77, 46, 20, 95, 61, 27, 60, 81, 19,  8, 64, 10, 90, 19])

In [56]:
b = np.random.randint(1,100,24).reshape(6,4)

In [57]:
b

array([[38, 66, 19, 90],
       [91,  4, 98, 65],
       [71,  7, 93, 54],
       [31, 32, 82, 75],
       [47, 78, 37,  5],
       [83, 18, 27, 29]])

## np.sort
Return a sorted copy of an array.

In [58]:
np.sort(a)

array([ 8, 10, 19, 19, 20, 27, 46, 60, 61, 64, 65, 77, 81, 90, 95])

In [59]:
np.sort(b)
#default rowwise sorting
np.sort(b,axis=0)
#this sorts colum wise

array([[31,  4, 19,  5],
       [38,  7, 27, 29],
       [47, 18, 37, 54],
       [71, 32, 82, 65],
       [83, 66, 93, 75],
       [91, 78, 98, 90]])

## np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [60]:
#append
np.append(a,200)

array([ 65,  77,  46,  20,  95,  61,  27,  60,  81,  19,   8,  64,  10,
        90,  19, 200])

In [61]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[3.80000000e+01, 6.60000000e+01, 1.90000000e+01, 9.00000000e+01,
        2.58988711e-01],
       [9.10000000e+01, 4.00000000e+00, 9.80000000e+01, 6.50000000e+01,
        4.93236477e-01],
       [7.10000000e+01, 7.00000000e+00, 9.30000000e+01, 5.40000000e+01,
        2.67357308e-02],
       [3.10000000e+01, 3.20000000e+01, 8.20000000e+01, 7.50000000e+01,
        5.60729919e-01],
       [4.70000000e+01, 7.80000000e+01, 3.70000000e+01, 5.00000000e+00,
        5.57330798e-01],
       [8.30000000e+01, 1.80000000e+01, 2.70000000e+01, 2.90000000e+01,
        1.34808876e-01]])

## np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

In [62]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

In [63]:
np.concatenate((c,d),axis=0) #h-stack
np.concatenate((c,d),axis=1) #v-stack

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [64]:
e=np.array([1,1,1,2,3,3,4,5,5,9])
np.unique(e)

array([1, 2, 3, 4, 5, 9])

In [65]:
a

array([65, 77, 46, 20, 95, 61, 27, 60, 81, 19,  8, 64, 10, 90, 19])

## np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [66]:
np.expand_dims(a,axis=0).shape #row mtrix
np.expand_dims(a,axis=1).shape #column matrix

(15, 1)

## np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [67]:
#find all indices with value greater than 50
np.where(a>50) #returns index value

(array([ 0,  1,  4,  5,  7,  8, 11, 13], dtype=int64),)

In [68]:
#replace all values greater than 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 46, 20,  0,  0, 27,  0,  0, 19,  8,  0, 10,  0, 19])

## np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [69]:
np.argmax(a) #finds index of maximum item

4

In [70]:
b

array([[38, 66, 19, 90],
       [91,  4, 98, 65],
       [71,  7, 93, 54],
       [31, 32, 82, 75],
       [47, 78, 37,  5],
       [83, 18, 27, 29]])

In [71]:
np.argmax(b, axis=0) #returns maximum value indices column wise

array([1, 4, 1, 0], dtype=int64)

In [72]:
np.argmax(b, axis=1) #returns maximum value indices row wise

array([3, 2, 2, 2, 1, 0], dtype=int64)

In [73]:
np.argmin(a) #similar to argmax() fucntions returns indices of minimum item

10

## np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [74]:
np.cumsum(a)

array([ 65, 142, 188, 208, 303, 364, 391, 451, 532, 551, 559, 623, 633,
       723, 742])

In [75]:
np.cumsum(b) #return 1d array 

array([  38,  104,  123,  213,  304,  308,  406,  471,  542,  549,  642,
        696,  727,  759,  841,  916,  963, 1041, 1078, 1083, 1166, 1184,
       1211, 1240])

In [76]:
np.cumsum(b,axis=1) #return cumsum row wise

array([[ 38, 104, 123, 213],
       [ 91,  95, 193, 258],
       [ 71,  78, 171, 225],
       [ 31,  63, 145, 220],
       [ 47, 125, 162, 167],
       [ 83, 101, 128, 157]])

In [77]:
np.cumsum(b,axis=0) #return cumsum column wise

array([[ 38,  66,  19,  90],
       [129,  70, 117, 155],
       [200,  77, 210, 209],
       [231, 109, 292, 284],
       [278, 187, 329, 289],
       [361, 205, 356, 318]])

In [78]:
np.cumprod(a) #similar to cumsum()

array([         65,        5005,      230230,     4604600,   437437000,
         913853224, -1095766728, -1321494240,   333148960,  2034862944,
        -900965632, -1827225600, -1092386816,   469434368,   329318400])

## np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [79]:
np.percentile(a,100) #return values havung 100 %tile
np.percentile(a,0) #returns vlaue having 0 %tile
np.percentile(a,50) #returns value having 50 %tile

60.0

## np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [80]:
np.histogram(a,bins=[10,20,30,40,50,60,70,80,90,100])

(array([3, 2, 0, 1, 0, 4, 1, 1, 2], dtype=int64),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef
Return Pearson product-moment correlation coefficients.

In [81]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

In [82]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [83]:
items=[10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([20, 60, 10, 90])

## np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [84]:
print(a)
np.flip(a)

[65 77 46 20 95 61 27 60 81 19  8 64 10 90 19]


array([19, 90, 10, 64,  8, 19, 81, 60, 27, 61, 95, 20, 46, 77, 65])

In [85]:
np.flip(b)
np.flip(b,axis=0) #column flip
np.flip(b,axis=1) #row flip

array([[90, 19, 66, 38],
       [65, 98,  4, 91],
       [54, 93,  7, 71],
       [75, 82, 32, 31],
       [ 5, 37, 78, 47],
       [29, 27, 18, 83]])

## np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [86]:
np.put(a,[0,1],[110,70]) #permanent change
a

array([110,  70,  46,  20,  95,  61,  27,  60,  81,  19,   8,  64,  10,
        90,  19])

## np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [87]:
np.delete(a,[0,2]) #delete on specified index

array([70, 20, 95, 61, 27, 60, 81, 19,  8, 64, 10, 90, 19])

## Set functions
* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d
* np.in1d

In [88]:
#set functions
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [89]:
np.intersect1d(m,n)

array([3, 4, 5])

In [90]:
np.setdiff1d(m,n)

array([1, 2])

In [91]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [92]:
np.in1d(m,1)

array([ True, False, False, False, False])

## np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

In [93]:
np.clip(a,a_min=25,a_max=75)

array([75, 70, 46, 25, 75, 61, 27, 60, 75, 25, 25, 64, 25, 75, 25])