## What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## Numpy Arrays Vs Python Sequences
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# creating numpy arrays

In [125]:
import numpy as np

In [126]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [127]:
b= np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [128]:
c=np.array([[[1,2],[3,4]],[[1,4],[3,4]]])
print(c)

[[[1 2]
  [3 4]]

 [[1 4]
  [3 4]]]


In [129]:
np.array([1,2,3],dtype=float)
#similar with other datatype

array([1., 2., 3.])

In [130]:
np.arange(1,11,2)
#similar to range function

array([1, 3, 5, 7, 9])

In [131]:
np.arange(1,13).reshape(2,6)
#changes dimensions of a nparray

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [132]:
np.ones((3,4))
#use -> initializes matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [133]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
np.random.random((3,4))

array([[0.64326363, 0.73609539, 0.50731822, 0.74270433],
       [0.47044941, 0.6336952 , 0.92583423, 0.49553355],
       [0.60447363, 0.09682548, 0.61559157, 0.59472952]])

In [135]:
np.linspace(-10,10,10,dtype=int)
#lower-range.upper-range,number-of-elements
#default datatype -> float

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [136]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attributes

In [137]:
a1=np.arange(10,dtype=np.int64)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8,dtype=np.int32).reshape(2,2,2)

In [138]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
#tells dimensions

1
2
3


In [139]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [140]:
a3.size
#number of elements

8

In [141]:
print(a3.itemsize)
print(a1.itemsize)

4
8


In [142]:
a1.dtype

dtype('int64')

# changing data type

In [143]:
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# array operations

In [144]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

print(a1)

print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## scalar operations


### arithmatic operations
(a1+2,a2-3,a1/3,a1*4,a1**5)

### relational operations

In [145]:
#comparison(>,<,>=,<=,==)
a1==3

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [146]:
a1>4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

## Vector operations

In [147]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# ARRAY FUNCTIONS

In [148]:
a1=np.random.random((3,3))
a1=np.round(a1*100)

In [149]:
a1

array([[ 6., 83., 78.],
       [97., 38.,  2.],
       [76., 44., 47.]])

In [150]:
#max/min/sum/product

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

97.0
2.0
471.0
45006309114624.0


In [151]:
#0-> column 1-> row
#max of row
np.max(a1,axis=1)

array([83., 97., 76.])

In [152]:
#statical functions
#mean/median/std/var


print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

52.333333333333336
47.0
31.864295588218067
1015.3333333333334


In [153]:
#trignometric functions
np.sin(a1)

array([[-0.2794155 ,  0.96836446,  0.51397846],
       [ 0.37960774,  0.29636858,  0.90929743],
       [ 0.56610764,  0.01770193,  0.12357312]])

In [154]:
# dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [155]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [156]:
#log and exponents

np.log(a1)
np.exp(a1)

array([[4.03428793e+02, 1.11286375e+36, 7.49841700e+33],
       [1.33833472e+42, 3.18559318e+16, 7.38905610e+00],
       [1.01480039e+33, 1.28516001e+19, 2.58131289e+20]])

In [157]:
#round/floor/ceil
print(np.round(np.random.random((2,3))*100)) 
print(np.floor(np.random.random((2,3))*100)) #last int
print(np.ceil(np.random.random((2,3))*100)) #6.1 -> 7

[[75. 45.  0.]
 [63. 40. 69.]]
[[90. 33. 28.]
 [27. 44. 19.]]
[[21. 26.  3.]
 [ 3. 66. 14.]]


# indexing and slicing

In [158]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(27).reshape(3,3,3)

## fetching element from matrix => INDEXING

In [159]:
a1[0]
a1[-1]

9

In [160]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
#find 4 in a2
a2[1,0]

#find 10
a2[2,2]

10

In [162]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [163]:
# find 3 in a3
a3[1,0,1]

#find 2
a3[0,1,0]

#find 0
a3[0,0,0]

#find 6
a3[1,1,0]

12

## FETCHING MULTIPLE ITEMS = SLICING

In [164]:
a1[2:5]

array([2, 3, 4])

In [165]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
#find 1st row all col
a2[0]

#find 3rd col
a2[:,2]

#find 5,6,9,10
a2[1:,1:3]

#find 0 3 8 11
a2[::2,::3]

#find 1 3 9 11
a2[::2,1::2]

#find 4 7
a2[1,::3]

#find 1 2 3, 5 6 7
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [167]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [168]:
#find 2nd row
a3[1]

#find 1st and 3rd 2d aray
a3[::2]

#find 1st ar 2nd row
a3[0,1]

#find 2nd ar middle column
a3[1,:,1]

#find 22 23 25 26
a3[2,1:,1:]

#find 0 2 18 20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [169]:
#ITERATING

In [170]:
for i in a1:
    print(i,end=',')

0,1,2,3,4,5,6,7,8,9,

In [171]:
for i in np.nditer(a3):
    print(i,end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,

# RESHAPING

In [172]:
#RESHAPE

#transpose
np.transpose(a2)
a2.T

#ravel -> coverts nd array into 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# STACKING

In [173]:
#HORIZONTAL STACKING (shape shound be same)
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [174]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [175]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# SPLITING

In [176]:
#horizontal spliting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [177]:
#vertical spliting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]